In [27]:
import numpy as np

In [28]:
a = np.arange(16)

In [29]:
np.random.shuffle(a)

In [30]:
a

array([ 3, 13, 10,  0,  9,  6,  7, 14,  5,  2,  1,  8, 12, 15, 11,  4])

In [31]:
a = a.reshape(4,-1)
a

array([[ 3, 13, 10,  0],
       [ 9,  6,  7, 14],
       [ 5,  2,  1,  8],
       [12, 15, 11,  4]])

In [32]:
a = a[a[:,1].argsort()]
a

array([[ 5,  2,  1,  8],
       [ 9,  6,  7, 14],
       [ 3, 13, 10,  0],
       [12, 15, 11,  4]])